---

# - name: Check mounted files existance
#   stat: path=/media/1Gig
#   register: st

# - name: Create the new dirs in /media
#   when: st.stat.exists == False
#   shell: sudo mkdir /media/1Gig
#   register: mkdir_media
#   sudo: yes

# - name: Mount the relevant dirs
#   when: mkdir_media|success
#   shell: sudo mount -t auto /dev/sda1 /media/1Gig

# - name: Install Samba
#   apt: pkg=samba state=installed update_cache=true
#   register: samba_installed
#   notify:
#     - Reload Samba

# - name: Backup old samba conf
#   when: samba_installed|success
#   command: sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.old
#   register: backup_old_samba_config

- name: Copy in samba config
  #when: backup_old_samba_config|success
  copy: src=samba.conf dest=/etc/samba/smb.conf owner=root group=root
  register: samba_config
  notify:
    - Reload Samba

# - name: Append a mount instruction to fstab to fstab
#   blockinfile:
#     dest: /etc/fstab
#     block: |
#       /dev/sda1 /media/1Gig auto users,noatime,umask=0 0 0

# - name: Allow SSH 22 Traffic
#   ufw: rule=allow port=22 proto=tcp
# - name: Allow Samba 445 Traffic
#   ufw: rule=allow port=445 proto=tcp
# - name: Allow Samba 137 Traffic
#   ufw: rule=allow port=137 proto=tcp
# - name: Allow Samba 138 Traffic
#   ufw: rule=allow port=138 proto=tcp
# - name: Allow Samba 139 Traffic
#   ufw: rule=allow port=139 proto=tcp


